services:
  backend:
    image: ghcr.io/embrs/asp-ci-demo:latest
    restart: always
    expose:
      - '5000'
    networks:
      - appnet
  frontend:
    image: ghcr.io/embrs/nuxt-ci-test:latest
    expose:
      - '3000'
    depends_on:
      - backend
    restart: always
    networks:
      - appnet
  nginx:
    image: nginx:alpine          # 使用輕量 Alpine 版本
    ports:
      - "80:80"                  # 映射 HTTP 端口
      - "443:443"                # 若有 HTTPS 需映射 443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # 掛載自定義配置
      - ./nginx/ssl:/etc/nginx/ssl:/etc/nginx/ssl;          # 掛載 SSL 憑證
    depends_on:
      - backend
      - frontend
    networks:
      - appnet
networks:
  appnet:
