services:
  frontend:
    image: ghcr.io/embrs/nuxt-ci-test:1.2.14
    expose:
      - '3000'
    restart: always
    networks:
      - appnet

  # backend:
  #   image: ghcr.io/embrs/php-ci-demo:1.0.2
  #   restart: always
  #   expose:
  #     - '8000'
  #   networks:
  #     - appnet
  backend:
    image: ghcr.io/embrs/asp-ci-demo:latest
    restart: always
    expose:
      - '5000'
    networks:
      - appnet
  nginx:
      image: ghcr.io/embrs/nginx-ci-demo:latest
      ports:
        - '80:80'
      depends_on:
        - frontend
        - backend
      networks:
        - appnet
networks:
  appnet:
