services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: harryrelease
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: mydb
    expose:
      - '5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # healthcheck:
    #   test: ['CMD-SHELL', 'pg_isready -U postgres']
    #   interval: 5s
    #   timeout: 5s
    #   retries: 5
    networks:
      - appnet

  backend1:
    image: ghcr.io/embrs/asp-ci-demo-dev:latest
    restart: always
    expose:
      - '5000'
    # depends_on:
    #   - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=mydb;Username=harryrelease;Password=12345
    networks:
      - appnet
  backend2:
    image: ghcr.io/embrs/asp-ci-demo-dev:latest
    restart: always
    expose:
      - '5000'
    # depends_on:
    #   - postgres
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=mydb;Username=harryrelease;Password=12345
    networks:
      - appnet
  frontend1:
    image: ghcr.io/embrs/nuxt-ci-test:latest
    expose:
      - '3000'
    restart: always
    networks:
      - appnet

  nginx:
    image: nginx:alpine          # 使用輕量 Alpine 版本
    ports:
      - "80:80"                  # 映射 HTTP 端口
      - "443:443"                # 若有 HTTPS 需映射 443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf  # 掛載自定義配置
      - ./nginx/ssl:/etc/nginx/ssl:/etc/nginx/ssl;          # 掛載 SSL 憑證
    depends_on:
      - backend1
      - backend2
      - frontend1
    networks:
      - appnet
volumes:
  postgres-data: {}   # 定義卷 postgres-data
networks:
  appnet:
