services:
  # backend:
  #   image: ghcr.io/embrs/php-ci-demo:latest
  #   restart: always
  #   expose:
  #     - '8000'
  #   networks:
  #     - appnet
  backend:
    image: ghcr.io/embrs/asp-ci-demo:latest
    restart: always
    expose:
      - '80'
    networks:
      - appnet
  frontend:
    image: ghcr.io/embrs/nuxt-ci-test:latest
    expose:
      - '3000'
    depends_on:
      - backend
    restart: always
    networks:
      - appnet
  nginx:
    image: nginx           # 使用輕量 Alpine 版本
    ports:
      - "80:80"                  # 映射 HTTP 端口
      # - "443:443"                # 若有 HTTPS 需映射 443
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # 掛載自定義配置
    networks:
      - appnet
networks:
  appnet:
