version: '3.9'

services:
  nginx:
    build: ./nginx
    ports:
      - '80:80'
    depends_on:
      - frontend
      - backend
    networks:
      - appnet

  frontend:
    build: ./frontend
    expose:
      - '3000'
    networks:
      - appnet

  backend:
    build: ./backend
    expose:
      - '8000'
    networks:
      - appnet

networks:
  appnet:
